language: node_js # 你用啥语言？这里node
node_js:
  - '8' # 你想在哪个版本的node下运行你的代码？这里是node 8
install: # 安装依赖环境
  - npm install
script: # 你要执行的脚本，构建当然是npm run build啦 
  - npm run build
branches: #构建哪些分支？master
  only:
    - master